behaviors:
  TetrisAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.7
      curiosity:
        strength: 0.9
        gamma: 0.99
        encoding_size: 256
    max_steps: 5000000
    summary_freq: 50000
    time_horizon: 64
    keep_checkpoints: 5